In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
from scipy import stats

In [20]:
df=pd.read_csv("C:/Users/prash/Pictures/Group 4_ForestCoverType/covtype.csv")
df.columns=['Elevation','Aspect','Slope','Horizontal_Distance_To_Hydrology',
                        'Vertical_Distance_To_Hydrology','Horizontal_Distance_To_Roadways',
                        'Hillshade_9am','Hillshade_Noon','Hillshade_3pm',
                        'Horizontal_Distance_To_Fire_Points','Rawah_Wilderness_Area','Neota_Wilderness_Area',
            'Comanche_Peak_Wilderness_Area','Cache_la_Poudre_Wilderness_Area',"Soil_code_2702",
                        "Soil_code_2703","Soil_code_2704","Soil_code_2705","Soil_code_2706","Soil_code_2717",
                        "Soil_code_3501","Soil_code_3502","Soil_code_4201","Soil_code_4703","Soil_code_4704",
                        "Soil_code_4744","Soil_code_4758","Soil_code_5101","Soil_code_5151","Soil_code_6101",
                        "Soil_code_6102","Soil_code_6731","Soil_code_7101","Soil_code_7102","Soil_code_7103",
                        "Soil_code_7201","Soil_code_7202","Soil_code_7700","Soil_code_7701","Soil_code_7702",
                        "Soil_code_7709","Soil_code_7710","Soil_code_7745","Soil_code_7746","Soil_code_7755",
                        "Soil_code_7756","Soil_code_7757","Soil_code_7790","Soil_code_8703","Soil_code_8707",
                        "Soil_code_8708","Soil_code_8771","Soil_code_8772","Soil_code_8776",'Cover_Type']

In [21]:
df['Distance_To_Hydrology']=np.round(np.sqrt(df['Horizontal_Distance_To_Hydrology']**2+
                                             df['Vertical_Distance_To_Hydrology']**2),2)
df['Hillshade']=np.round((df['Hillshade_9am']+df['Hillshade_Noon']+df['Hillshade_3pm'])/3,2)

In [22]:
pd.set_option('display.max_columns', None)

In [23]:
numerical=['Elevation','Aspect','Slope','Distance_To_Hydrology',
           'Horizontal_Distance_To_Roadways','Hillshade','Horizontal_Distance_To_Fire_Points']
categorical=['Rawah_Wilderness_Area','Neota_Wilderness_Area','Comanche_Peak_Wilderness_Area',
             'Cache_la_Poudre_Wilderness_Area',"Soil_code_2702","Soil_code_2703","Soil_code_2704","Soil_code_2705",
             "Soil_code_2706","Soil_code_2717","Soil_code_3501","Soil_code_3502","Soil_code_4201","Soil_code_4703",
             "Soil_code_4704","Soil_code_4744","Soil_code_4758","Soil_code_5101","Soil_code_5151","Soil_code_6101",
             "Soil_code_6102","Soil_code_6731","Soil_code_7101","Soil_code_7102","Soil_code_7103","Soil_code_7201",
             "Soil_code_7202","Soil_code_7700","Soil_code_7701","Soil_code_7702","Soil_code_7709","Soil_code_7710",
             "Soil_code_7745","Soil_code_7746","Soil_code_7755","Soil_code_7756","Soil_code_7757","Soil_code_7790",
             "Soil_code_8703","Soil_code_8707","Soil_code_8708","Soil_code_8771","Soil_code_8772","Soil_code_8776"]
target=['Cover_Type']

In [6]:
df['Soil']=df[categorical[4:]].idxmax(axis=1)
def cg(x):
    if x[-4:-2]=='27':
        return 'cgzone_27'
    if x[-4:-2]=='35':
        return 'cgzone_35'
    if x[-4:-2]=='42':
        return 'cgzone_42'
    if x[-4:-2]=='47':
        return 'cgzone_47'
    if x[-4:-2]=='51':
        return 'cgzone_51'
    if x[-4:-2]=='61':
        return 'cgzone_61'
    if x[-4:-2]=='67':
        return 'cgzone_67'
    if x[-4:-2]=='71':
        return 'cgzone_71'
    if x[-4:-2]=='72':
        return 'cgzone_72'
    if x[-4:-2]=='77':
        return 'cgzone_77'
    if x[-4:-2]=='87':
        return 'cgzone_87'
df['cgzone']=df['Soil'].apply(lambda x:cg(x))
df.drop(categorical[4:],axis=1, inplace=True)
df['Wilderness_Area']=df[categorical[0:4]].idxmax(axis=1)
df.drop(categorical[0:4],axis=1, inplace=True)

In [7]:
df.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Cover_Type,Distance_To_Hydrology,Hillshade,Soil,cgzone,Wilderness_Area
0,2590,56,2,212,-6,390,220,235,151,6225,5,212.08,202.00,Soil_code_7745,cgzone_77,Rawah_Wilderness_Area
1,2804,139,9,268,65,3180,234,238,135,6121,2,275.77,202.33,Soil_code_4744,cgzone_47,Rawah_Wilderness_Area
2,2785,155,18,242,118,3090,238,238,122,6211,2,269.24,199.33,Soil_code_7746,cgzone_77,Rawah_Wilderness_Area
3,2595,45,2,153,-1,391,220,234,150,6172,5,153.00,201.33,Soil_code_7745,cgzone_77,Rawah_Wilderness_Area
4,2579,132,6,300,-15,67,230,237,140,6031,2,300.37,202.33,Soil_code_7745,cgzone_77,Rawah_Wilderness_Area

In [8]:
import scipy.stats as stats

## CATEGORICAL VS CATEGORICAL

### Wilderness_Area vs Cover_Type
H0: There is no association b/w Wilderness_Area vs Cover_Type             
H1: There is an association b/w Wilderness_Area vs Cover_Type

In [9]:
tab=pd.crosstab(df['Wilderness_Area'],df['Cover_Type'])
tab

Cover_Type,1,2,3,4,5,6,7
Wilderness_Area,,,,,,,
Cache_la_Poudre_Wilderness_Area,0,3026,21454,2747,0,9741,0
Comanche_Peak_Wilderness_Area,87528,125093,14300,0,5712,7626,13105
Neota_Wilderness_Area,18595,8985,0,0,0,0,2304
Rawah_Wilderness_Area,105717,146197,0,0,3780,0,5101

In [10]:
a=stats.chi2_contingency(tab)
print('Chi2 is ',a[0])
print('P-value is ',a[1])
print('DOF is ',a[2])
print('Expected Values is ',a[3])

Chi2 is  342443.36649246264
P-value is  0.0
DOF is  18
Expected Values is  [[ 13478.74845743  18025.59911602   2274.92056433    174.78343095
     603.94769806   1105.01050066   1304.99023254]
 [ 92377.99243044 123540.30227311  15591.4026688    1197.89626702
    4139.21782548   7573.30341078   8943.88512438]
 [ 10895.88073203  14571.44027222   1838.98848042    141.2905229
     488.21610606    893.26265424   1054.92123213]
 [ 95087.3783801  127163.65833865  16048.68828645   1233.02977913
    4260.61837039   7795.42343432   9206.20341095]]

#### conclusion: Since the P-value(0)<alpha(0.05) rejecting H0 there is an association between the Wilderness_Area vs Cover_Type.

### cgzone vs Cover_Type
H0: There is no association b/w cgzone vs Cover_Type             
H1: There is an association b/w cgzone vs Cover_Type

In [11]:
tab=pd.crosstab(df['cgzone'],df['Cover_Type'])
tab

Cover_Type       1       2      3     4     5     6      7
cgzone
cgzone_27      182    6206  21964  1847   849  4821     78
cgzone_35       43     241      0     0     0     0      0
cgzone_42      161     986      0     0     0     0      0
cgzone_47     6593   60416  12926   258  2256  9991      6
cgzone_51        0       0    116   155     0   331      0
cgzone_61      850    2700    635   487   635   960      0
cgzone_67       70    1659      0     0   170     0      0
cgzone_71     6982    6718      2     0   120   280     16
cgzone_72    61340   28203      0     0   699    29    854
cgzone_77   113237  174688    111     0  4763   955   2985
cgzone_87    22382    1484      0     0     0     0  16571

In [12]:
a=stats.chi2_contingency(tab)
print('Chi2 is ',a[0])
print('P-value is ',a[1])
print('DOF is ',a[2])
print('Expected Values is ',a[3])

Chi2 is  584631.2305386869
P-value is  0.0
DOF is  60
Expected Values is  [[1.31064859e+04 1.75277595e+04 2.21209071e+03 1.69956178e+02
  5.87267580e+02 1.07449179e+03 1.26894838e+03]
 [1.03548057e+02 1.38478418e+02 1.74766674e+01 1.34274222e+00
  4.63971939e+00 8.48904410e+00 1.00253524e+01]
 [4.18202891e+02 5.59277272e+02 7.05835828e+01 5.42297650e+00
  1.87385850e+01 3.42849774e+01 4.04897153e+01]
 [3.37063509e+04 4.50766754e+04 5.68890139e+03 4.37081504e+02
  1.51029401e+03 2.76330342e+03 3.26339340e+03]
 [2.19492712e+02 2.93535238e+02 3.70456119e+01 2.84623527e+00
  9.83489813e+00 1.79943822e+01 2.12509230e+01]
 [2.28498476e+03 3.05578959e+03 3.85655896e+02 2.96301602e+01
  1.02384230e+02 1.87326899e+02 2.21228462e+02]
 [6.92386478e+02 9.25952519e+02 1.16859829e+02 8.97840661e+00
  3.10240391e+01 5.67630097e+01 6.70357188e+01]
 [5.14750516e+03 6.88393768e+03 8.68787290e+02 6.67494178e+01
  2.30646332e+02 4.22001143e+02 4.98372974e+02]
 [3.32247066e+04 4.44325557e+04 5.60761027e+03 4.30835862e+02
  1.48871278e+03 2.72381741e+03 3.21676139e+03]
 [1.08192770e+05 1.44689955e+05 1.82605944e+04 1.40297177e+03
  4.84783694e+03 8.86982555e+03 1.04750459e+04]
 [1.47435661e+04 1.97170837e+04 2.48839436e+03 1.91184743e+02
  6.60620890e+02 1.20870238e+03 1.42744779e+03]]

#### conclusion: Since the P-value(0)<alpha(0.05) rejecting H0 there is an association between the cgzone vs Cover_Type.

### Soil vs Cover_Type
H0: There is no association b/w Soil vs Cover_Type             
H1: There is an association b/w Soil vs Cover_Type

In [13]:
tab=pd.crosstab(df['Soil'],df['Cover_Type'])
tab

Cover_Type          1      2      3     4     5     6     7
Soil
Soil_code_2702      0      0   2101   178     0   752     0
Soil_code_2703      0    852   4991   115   264  1303     0
Soil_code_2704      0   1191   2411  1018     0   203     0
Soil_code_2705    182   3251   7501   168   585   631    78
Soil_code_2706      0      0    967    48     0   582     0
Soil_code_2717      0    912   3993   320     0  1350     0
Soil_code_3501      0    105      0     0     0     0     0
Soil_code_3502     43    136      0     0     0     0     0
Soil_code_4201    161    986      0     0     0     0     0
Soil_code_4703    956  10803  11532   224   260  8859     0
Soil_code_4704    747   9077   1353    34   681   518     0
Soil_code_4744   2693  27278      0     0     0     0     0
Soil_code_4758   2197  13258     41     0  1315   614     6
Soil_code_5101      0      0    116   155     0   328     0
Soil_code_5151      0      0      0     0     0     3     0
Soil_code_6101    636   1743    129    51    35   251     0
Soil_code_6102    214    957    506   436   600   709     0
Soil_code_6731     70   1659      0     0   170     0     0
Soil_code_7101   2461   1490      0     0    67     0     3
Soil_code_7102   3717   5207      2     0    53   280     0
Soil_code_7103    804     21      0     0     0     0    13
Soil_code_7201  25783   7442      0     0     0     0   148
Soil_code_7202  35557  20761      0     0   699    29   706
Soil_code_7700  11164   9702      0     0    70   138   204
Soil_code_7701    125    349      0     0     0     0     0
Soil_code_7702    283   2174      0     0   132     0     0
Soil_code_7709    604    451      0     0     0     0    31
Soil_code_7710     43    891      0     0    12     0     0
Soil_code_7745  41911  71399      0     0  1131     0   805
Soil_code_7746   7644  20218      0     0  2111     0   197
Soil_code_7755  11863  13209      0     0   309    63   222
Soil_code_7756  21358  29556    106     0   460   200   839
Soil_code_7757  18148  25308      5     0   518   539   636
Soil_code_7790     94   1431      0     0    20    15    51
Soil_code_8703    931     12      0     0     0     0   948
Soil_code_8707     14     42      0     0     0     0    63
Soil_code_8708      0      0      0     0     0     0   298
Soil_code_8771   8729    740      0     0     0     0  6104
Soil_code_8772   7882    358      0     0     0     0  5566
Soil_code_8776   4826    332      0     0     0     0  3592

In [14]:
a=stats.chi2_contingency(tab)
print('Chi2 is ',a[0])
print('P-value is ',a[1])
print('DOF is ',a[2])
print('Expected Values is ',a[3])

Chi2 is  762248.2993749469
P-value is  0.0
DOF is  234
Expected Values is  [[1.10512028e+03 1.47791579e+03 1.86520348e+02 1.43304636e+01
  4.95175685e+01 9.05996220e+01 1.06995926e+02]
 [2.74365890e+03 3.66919047e+03 4.63070148e+02 3.55779409e+01
  1.22936227e+02 2.24929778e+02 2.65636537e+02]
 [1.75849394e+03 2.35169510e+03 2.96795658e+02 2.28029779e+01
  7.87935444e+01 1.44164295e+02 1.70254487e+02]
 [4.51965391e+03 6.04429038e+03 7.62819609e+02 5.86078611e+01
  2.02513949e+02 3.70528840e+02 4.37585450e+02]
 [5.82275516e+02 7.78697300e+02 9.82754853e+01 7.55056100e+00
  2.60902530e+01 4.77359275e+01 5.63749568e+01]
 [2.39728336e+03 3.20597041e+03 4.04609465e+02 3.10863736e+01
  1.07416039e+02 1.96533327e+02 2.32101027e+02]
 [3.82836125e+01 5.11980066e+01 6.46144393e+00 4.96436384e-01
  1.71538921e+00 3.13855504e+00 3.70655633e+00]
 [6.52644442e+01 8.72804112e+01 1.10152235e+01 8.46305836e-01
  2.92433018e+00 5.35048906e+00 6.31879603e+00]
 [4.18202891e+02 5.59277272e+02 7.05835828e+01 5.42297650e+00
  1.87385850e+01 3.42849774e+01 4.04897153e+01]
 [1.18985468e+04 1.59123404e+04 2.00821677e+03 1.54292428e+02
  5.33142966e+02 9.75462905e+02 1.15199771e+03]
 [4.52475840e+03 6.05111678e+03 7.63681135e+02 5.86740526e+01
  2.02742668e+02 3.70947314e+02 4.38079658e+02]
 [1.09276014e+04 1.46138615e+04 1.84434225e+03 1.41701856e+02
  4.89637429e+02 8.95863171e+02 1.05799238e+03]
 [6.35544429e+03 8.49935669e+03 1.07266123e+03 8.24131677e+01
  2.84770946e+02 5.21030027e+02 6.15323651e+02]
 [2.18398894e+02 2.92072438e+02 3.68609992e+01 2.83205137e+00
  9.78588701e+00 1.79047092e+01 2.11450214e+01]
 [1.09381750e+00 1.46280019e+00 1.84612684e-01 1.41838967e-02
  4.90111203e-02 8.96730010e-02 1.05901609e-01]
 [1.03730360e+03 1.38722218e+03 1.75074362e+02 1.34510620e+01
  4.64788791e+01 8.50398960e+01 1.00430026e+02]
 [1.24768116e+03 1.66856741e+03 2.10581535e+02 1.61790982e+01
  5.59053512e+01 1.02287003e+02 1.20798436e+02]
 [6.92386478e+02 9.25952519e+02 1.16859829e+02 8.97840661e+00
  3.10240391e+01 5.67630097e+01 6.70357188e+01]
 [1.46608006e+03 1.96063985e+03 2.47442534e+02 1.90111495e+01
  6.56912382e+01 1.20191712e+02 1.41943457e+02]
 [3.37588541e+03 4.51468898e+03 5.69776280e+02 4.37762332e+01
  1.51264654e+02 2.76760772e+02 3.26847667e+02]
 [3.05539689e+02 4.08608853e+02 5.15684763e+01 3.96203514e+00
  1.36904396e+01 2.50486583e+01 2.95818496e+01]
 [1.21679905e+04 1.62726769e+04 2.05369303e+03 1.57786395e+02
  5.45216039e+02 9.97552354e+02 1.17808480e+03]
 [2.10567161e+04 2.81598788e+04 3.55391724e+03 2.73049467e+02
  9.43496739e+02 1.72626505e+03 2.03867658e+03]
 [7.75808293e+03 1.03751541e+04 1.30939623e+03 1.00601651e+02
  3.47619539e+02 6.36020705e+02 7.51124815e+02]
 [1.72823165e+02 2.31122430e+02 2.91688040e+01 2.24105568e+00
  7.74375700e+00 1.41683342e+01 1.67324543e+01]
 [9.43964503e+02 1.26239656e+03 1.59320746e+02 1.22407028e+01
  4.22965968e+01 7.73877999e+01 9.13930889e+01]
 [3.95961935e+02 5.29533668e+02 6.68297915e+01 5.13457060e+00
  1.77420255e+01 3.24616264e+01 3.83363826e+01]
 [3.44917119e+02 4.61269659e+02 5.82145329e+01 4.47265542e+00
  1.54548399e+01 2.82768863e+01 3.33943075e+01]
 [4.20193639e+04 5.61939568e+04 7.09195778e+03 5.44879119e+02
  1.88277852e+03 3.44481823e+03 4.06824563e+03]
 [1.10001580e+04 1.47108939e+04 1.85658822e+03 1.42642721e+02
  4.92888500e+02 9.01811480e+02 1.06501719e+03]
 [9.35797333e+03 1.25147432e+04 1.57942305e+03 1.21347964e+02
  4.19306471e+02 7.67182415e+02 9.06023569e+02]
 [1.91487338e+04 2.56082677e+04 3.23189118e+03 2.48308023e+02
  8.58005009e+02 1.56984545e+03 1.85394888e+03]
 [1.64634118e+04 2.20170932e+04 2.77866704e+03 2.13486557e+02
  7.37682708e+02 1.34969823e+03 1.59396042e+03]
 [5.87379998e+02 7.85523701e+02 9.91370112e+01 7.61675252e+00
  2.63189716e+01 4.81544016e+01 5.68691643e+01]
 [6.89469631e+02 9.22051718e+02 1.16367528e+02 8.94058288e+00
  3.08933428e+01 5.65238816e+01 6.67533145e+01]
 [4.33880942e+01 5.80244075e+01 7.32296979e+00 5.62627902e-01
  1.94410777e+00 3.55702904e+00 4.20076384e+00]
 [1.08652538e+02 1.45304819e+02 1.83381933e+01 1.40893374e+00
  4.86843795e+00 8.90751810e+00 1.05195599e+01]
 [5.67800665e+03 7.59339578e+03 9.58324441e+02 7.36286077e+01
  2.54416725e+02 4.65492548e+02 5.49735255e+02]
 [5.03374814e+03 6.73180646e+03 8.49587571e+02 6.52742926e+01
  2.25549175e+02 4.12675151e+02 4.87359207e+02]
 [3.19030104e+03 4.26650055e+03 5.38453661e+02 4.13696987e+01
  1.42949101e+02 2.61546253e+02 3.08879694e+02]]

#### conclusion: Since the P-value(0)<alpha(0.05) rejecting H0 there is an association between the Soil vs Cover_Type.

### Soil vs Wilderness_Area
H0: There is no association b/w Soil vs Wilderness_Area             
H1: There is an association b/w Soil vs Wilderness_Area

In [15]:
tab=pd.crosstab(df['Soil'],df['Cover_Type'])
tab

Cover_Type          1      2      3     4     5     6     7
Soil
Soil_code_2702      0      0   2101   178     0   752     0
Soil_code_2703      0    852   4991   115   264  1303     0
Soil_code_2704      0   1191   2411  1018     0   203     0
Soil_code_2705    182   3251   7501   168   585   631    78
Soil_code_2706      0      0    967    48     0   582     0
Soil_code_2717      0    912   3993   320     0  1350     0
Soil_code_3501      0    105      0     0     0     0     0
Soil_code_3502     43    136      0     0     0     0     0
Soil_code_4201    161    986      0     0     0     0     0
Soil_code_4703    956  10803  11532   224   260  8859     0
Soil_code_4704    747   9077   1353    34   681   518     0
Soil_code_4744   2693  27278      0     0     0     0     0
Soil_code_4758   2197  13258     41     0  1315   614     6
Soil_code_5101      0      0    116   155     0   328     0
Soil_code_5151      0      0      0     0     0     3     0
Soil_code_6101    636   1743    129    51    35   251     0
Soil_code_6102    214    957    506   436   600   709     0
Soil_code_6731     70   1659      0     0   170     0     0
Soil_code_7101   2461   1490      0     0    67     0     3
Soil_code_7102   3717   5207      2     0    53   280     0
Soil_code_7103    804     21      0     0     0     0    13
Soil_code_7201  25783   7442      0     0     0     0   148
Soil_code_7202  35557  20761      0     0   699    29   706
Soil_code_7700  11164   9702      0     0    70   138   204
Soil_code_7701    125    349      0     0     0     0     0
Soil_code_7702    283   2174      0     0   132     0     0
Soil_code_7709    604    451      0     0     0     0    31
Soil_code_7710     43    891      0     0    12     0     0
Soil_code_7745  41911  71399      0     0  1131     0   805
Soil_code_7746   7644  20218      0     0  2111     0   197
Soil_code_7755  11863  13209      0     0   309    63   222
Soil_code_7756  21358  29556    106     0   460   200   839
Soil_code_7757  18148  25308      5     0   518   539   636
Soil_code_7790     94   1431      0     0    20    15    51
Soil_code_8703    931     12      0     0     0     0   948
Soil_code_8707     14     42      0     0     0     0    63
Soil_code_8708      0      0      0     0     0     0   298
Soil_code_8771   8729    740      0     0     0     0  6104
Soil_code_8772   7882    358      0     0     0     0  5566
Soil_code_8776   4826    332      0     0     0     0  3592

In [16]:
a=stats.chi2_contingency(tab)
print('Chi2 is ',a[0])
print('P-value is ',a[1])
print('DOF is ',a[2])
print('Expected Values is ',a[3])

Chi2 is  762248.2993749469
P-value is  0.0
DOF is  234
Expected Values is  [[1.10512028e+03 1.47791579e+03 1.86520348e+02 1.43304636e+01
  4.95175685e+01 9.05996220e+01 1.06995926e+02]
 [2.74365890e+03 3.66919047e+03 4.63070148e+02 3.55779409e+01
  1.22936227e+02 2.24929778e+02 2.65636537e+02]
 [1.75849394e+03 2.35169510e+03 2.96795658e+02 2.28029779e+01
  7.87935444e+01 1.44164295e+02 1.70254487e+02]
 [4.51965391e+03 6.04429038e+03 7.62819609e+02 5.86078611e+01
  2.02513949e+02 3.70528840e+02 4.37585450e+02]
 [5.82275516e+02 7.78697300e+02 9.82754853e+01 7.55056100e+00
  2.60902530e+01 4.77359275e+01 5.63749568e+01]
 [2.39728336e+03 3.20597041e+03 4.04609465e+02 3.10863736e+01
  1.07416039e+02 1.96533327e+02 2.32101027e+02]
 [3.82836125e+01 5.11980066e+01 6.46144393e+00 4.96436384e-01
  1.71538921e+00 3.13855504e+00 3.70655633e+00]
 [6.52644442e+01 8.72804112e+01 1.10152235e+01 8.46305836e-01
  2.92433018e+00 5.35048906e+00 6.31879603e+00]
 [4.18202891e+02 5.59277272e+02 7.05835828e+01 5.42297650e+00
  1.87385850e+01 3.42849774e+01 4.04897153e+01]
 [1.18985468e+04 1.59123404e+04 2.00821677e+03 1.54292428e+02
  5.33142966e+02 9.75462905e+02 1.15199771e+03]
 [4.52475840e+03 6.05111678e+03 7.63681135e+02 5.86740526e+01
  2.02742668e+02 3.70947314e+02 4.38079658e+02]
 [1.09276014e+04 1.46138615e+04 1.84434225e+03 1.41701856e+02
  4.89637429e+02 8.95863171e+02 1.05799238e+03]
 [6.35544429e+03 8.49935669e+03 1.07266123e+03 8.24131677e+01
  2.84770946e+02 5.21030027e+02 6.15323651e+02]
 [2.18398894e+02 2.92072438e+02 3.68609992e+01 2.83205137e+00
  9.78588701e+00 1.79047092e+01 2.11450214e+01]
 [1.09381750e+00 1.46280019e+00 1.84612684e-01 1.41838967e-02
  4.90111203e-02 8.96730010e-02 1.05901609e-01]
 [1.03730360e+03 1.38722218e+03 1.75074362e+02 1.34510620e+01
  4.64788791e+01 8.50398960e+01 1.00430026e+02]
 [1.24768116e+03 1.66856741e+03 2.10581535e+02 1.61790982e+01
  5.59053512e+01 1.02287003e+02 1.20798436e+02]
 [6.92386478e+02 9.25952519e+02 1.16859829e+02 8.97840661e+00
  3.10240391e+01 5.67630097e+01 6.70357188e+01]
 [1.46608006e+03 1.96063985e+03 2.47442534e+02 1.90111495e+01
  6.56912382e+01 1.20191712e+02 1.41943457e+02]
 [3.37588541e+03 4.51468898e+03 5.69776280e+02 4.37762332e+01
  1.51264654e+02 2.76760772e+02 3.26847667e+02]
 [3.05539689e+02 4.08608853e+02 5.15684763e+01 3.96203514e+00
  1.36904396e+01 2.50486583e+01 2.95818496e+01]
 [1.21679905e+04 1.62726769e+04 2.05369303e+03 1.57786395e+02
  5.45216039e+02 9.97552354e+02 1.17808480e+03]
 [2.10567161e+04 2.81598788e+04 3.55391724e+03 2.73049467e+02
  9.43496739e+02 1.72626505e+03 2.03867658e+03]
 [7.75808293e+03 1.03751541e+04 1.30939623e+03 1.00601651e+02
  3.47619539e+02 6.36020705e+02 7.51124815e+02]
 [1.72823165e+02 2.31122430e+02 2.91688040e+01 2.24105568e+00
  7.74375700e+00 1.41683342e+01 1.67324543e+01]
 [9.43964503e+02 1.26239656e+03 1.59320746e+02 1.22407028e+01
  4.22965968e+01 7.73877999e+01 9.13930889e+01]
 [3.95961935e+02 5.29533668e+02 6.68297915e+01 5.13457060e+00
  1.77420255e+01 3.24616264e+01 3.83363826e+01]
 [3.44917119e+02 4.61269659e+02 5.82145329e+01 4.47265542e+00
  1.54548399e+01 2.82768863e+01 3.33943075e+01]
 [4.20193639e+04 5.61939568e+04 7.09195778e+03 5.44879119e+02
  1.88277852e+03 3.44481823e+03 4.06824563e+03]
 [1.10001580e+04 1.47108939e+04 1.85658822e+03 1.42642721e+02
  4.92888500e+02 9.01811480e+02 1.06501719e+03]
 [9.35797333e+03 1.25147432e+04 1.57942305e+03 1.21347964e+02
  4.19306471e+02 7.67182415e+02 9.06023569e+02]
 [1.91487338e+04 2.56082677e+04 3.23189118e+03 2.48308023e+02
  8.58005009e+02 1.56984545e+03 1.85394888e+03]
 [1.64634118e+04 2.20170932e+04 2.77866704e+03 2.13486557e+02
  7.37682708e+02 1.34969823e+03 1.59396042e+03]
 [5.87379998e+02 7.85523701e+02 9.91370112e+01 7.61675252e+00
  2.63189716e+01 4.81544016e+01 5.68691643e+01]
 [6.89469631e+02 9.22051718e+02 1.16367528e+02 8.94058288e+00
  3.08933428e+01 5.65238816e+01 6.67533145e+01]
 [4.33880942e+01 5.80244075e+01 7.32296979e+00 5.62627902e-01
  1.94410777e+00 3.55702904e+00 4.20076384e+00]
 [1.08652538e+02 1.45304819e+02 1.83381933e+01 1.40893374e+00
  4.86843795e+00 8.90751810e+00 1.05195599e+01]
 [5.67800665e+03 7.59339578e+03 9.58324441e+02 7.36286077e+01
  2.54416725e+02 4.65492548e+02 5.49735255e+02]
 [5.03374814e+03 6.73180646e+03 8.49587571e+02 6.52742926e+01
  2.25549175e+02 4.12675151e+02 4.87359207e+02]
 [3.19030104e+03 4.26650055e+03 5.38453661e+02 4.13696987e+01
  1.42949101e+02 2.61546253e+02 3.08879694e+02]]

#### conclusion: Since the P-value(0)<alpha(0.05) rejecting H0 there is an association between the Soil vs Wilderness_Area.

# CONTINOUS VS CATEGORICAL (One way Anova)

In [26]:
## Assumptions : 1.Randomness 2.Normality 3.Variance equality
## 1: Assumed randomness

In [49]:
##2.Normality
for i in ['Elevation','Aspect','Slope','Horizontal_Distance_To_Hydrology','Vertical_Distance_To_Hydrology','Horizontal_Distance_To_Roadways',
          'Hillshade_9am','Hillshade_Noon','Hillshade_3pm','Horizontal_Distance_To_Fire_Points','Distance_To_Hydrology', 'Hillshade']:
    a=stats.shapiro(df[i])
    if float(a[1])<0.05:
        print(i,' does not follow normality')
    else:
        print(i,' follow normality')

Elevation  does not follow normality
Aspect  does not follow normality
Slope  does not follow normality
Horizontal_Distance_To_Hydrology  does not follow normality
Vertical_Distance_To_Hydrology  does not follow normality
Horizontal_Distance_To_Roadways  does not follow normality
Hillshade_9am  does not follow normality
Hillshade_Noon  does not follow normality
Hillshade_3pm  does not follow normality
Horizontal_Distance_To_Fire_Points  does not follow normality
Distance_To_Hydrology  does not follow normality
Hillshade  does not follow normality

In [48]:
#3.Variance equality
aa = df[df['Cover_Type']==1]
bb = df[df['Cover_Type']==2]
cc = df[df['Cover_Type']==3]
dd = df[df['Cover_Type']==4]
ee = df[df['Cover_Type']==5]
ff = df[df['Cover_Type']==6]
gg = df[df['Cover_Type']==7]
for i in ['Elevation','Aspect','Slope','Horizontal_Distance_To_Hydrology','Vertical_Distance_To_Hydrology','Horizontal_Distance_To_Roadways',
          'Hillshade_9am','Hillshade_Noon','Hillshade_3pm','Horizontal_Distance_To_Fire_Points','Distance_To_Hydrology', 'Hillshade']:
    abcd=stats.levene(aa[i],bb[i],cc[i],dd[i],ee[i],ff[i],gg[i])
    if float(abcd[1])<0.05:
        print('All input samples in from ', i,' does not have equal variances')
    else:
        print('All input samples in from ', i,' has equal variances')

All input samples in from  Elevation  does not have equal variances
All input samples in from  Aspect  does not have equal variances
All input samples in from  Slope  does not have equal variances
All input samples in from  Horizontal_Distance_To_Hydrology  does not have equal variances
All input samples in from  Vertical_Distance_To_Hydrology  does not have equal variances
All input samples in from  Horizontal_Distance_To_Roadways  does not have equal variances
All input samples in from  Hillshade_9am  does not have equal variances
All input samples in from  Hillshade_Noon  does not have equal variances
All input samples in from  Hillshade_3pm  does not have equal variances
All input samples in from  Horizontal_Distance_To_Fire_Points  does not have equal variances
All input samples in from  Distance_To_Hydrology  does not have equal variances
All input samples in from  Hillshade  does not have equal variances

In [50]:
for i in ['Elevation','Aspect','Slope','Horizontal_Distance_To_Hydrology','Vertical_Distance_To_Hydrology','Horizontal_Distance_To_Roadways',
          'Hillshade_9am','Hillshade_Noon','Hillshade_3pm','Horizontal_Distance_To_Fire_Points','Distance_To_Hydrology', 'Hillshade']:
    abcd=stats.kruskal(aa[i],bb[i],cc[i],dd[i],ee[i],ff[i],gg[i]) 
    if float(abcd[1])<0.05:
        print('All input samples in from ', i,' does not have equal variances')
    else:
        print('All input samples in from ', i,' has equal variances')

All input samples in from  Elevation  has equal variances
All input samples in from  Aspect  has equal variances
All input samples in from  Slope  has equal variances
All input samples in from  Horizontal_Distance_To_Hydrology  has equal variances
All input samples in from  Vertical_Distance_To_Hydrology  has equal variances
All input samples in from  Horizontal_Distance_To_Roadways  has equal variances
All input samples in from  Hillshade_9am  has equal variances
All input samples in from  Hillshade_Noon  has equal variances
All input samples in from  Hillshade_3pm  has equal variances
All input samples in from  Horizontal_Distance_To_Fire_Points  has equal variances
All input samples in from  Distance_To_Hydrology  has equal variances
All input samples in from  Hillshade  has equal variances

# Elevation vs Cover_Type

H0: mu_C1=mu_C2=mu_C3=mu_C4=mu_C5=mu_C6=mu_C7                    
H1: mu_C1!=mu_C2!=mu_C3!=mu_C4!=mu_C5!=mu_C6!=mu_C7

In [25]:
## Assumptions : 1.Randomness 2.Normality 3.Variance equality
## 1: assumed randomness
## 2: Normality is already checked, assume for a while it follow normal
## 3: variance equality (need to check)

# Multicolinearity Check

In [ ]:
df.drop(df.columns[9:49],axis=1,inplace=True)

In [24]:
df.drop(['Hillshade_9am','Hillshade_Noon','Hillshade_3pm',
         'Horizontal_Distance_To_Hydrology','Vertical_Distance_To_Hydrology'],axis=1, inplace=True)
df.drop(df.columns[9:49],axis=1,inplace=True)
from statsmodels.stats.outliers_influence import variance_inflation_factor
X=df.drop('Cover_Type',axis=1)
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif["features"] = X.columns
vif.round(1)

    VIF Factor                            features
0          2.2                           Elevation
1          1.4                              Aspect
2          2.0                               Slope
3          1.6     Horizontal_Distance_To_Roadways
4          1.3  Horizontal_Distance_To_Fire_Points
5        298.1               Rawah_Wilderness_Area
6         38.3               Neota_Wilderness_Area
7        295.2       Comanche_Peak_Wilderness_Area
8         37.3     Cache_la_Poudre_Wilderness_Area
9          1.2               Distance_To_Hydrology
10         2.2                           Hillshade

Index(['Soil_code_2702', 'Soil_code_2703', 'Soil_code_2704', 'Soil_code_2705',
       'Soil_code_2706', 'Soil_code_2717', 'Soil_code_3501', 'Soil_code_3502',
       'Soil_code_4201', 'Soil_code_4703', 'Soil_code_4704', 'Soil_code_4744',
       'Soil_code_4758', 'Soil_code_5101', 'Soil_code_5151', 'Soil_code_6101',
       'Soil_code_6102', 'Soil_code_6731', 'Soil_code_7101', 'Soil_code_7102',
       'Soil_code_7103', 'Soil_code_7201', 'Soil_code_7202', 'Soil_code_7700',
       'Soil_code_7701', 'Soil_code_7702', 'Soil_code_7709', 'Soil_code_7710',
       'Soil_code_7745', 'Soil_code_7746', 'Soil_code_7755', 'Soil_code_7756',
       'Soil_code_7757', 'Soil_code_7790', 'Soil_code_8703', 'Soil_code_8707',
       'Soil_code_8708', 'Soil_code_8771', 'Soil_code_8772', 'Soil_code_8776'],
      dtype='object')

# Summary

Since the P-value(0)<alpha(0.05) rejecting H0 there is an association between the Wilderness_Area vs Cover_Type.      
Since the P-value(0)<alpha(0.05) rejecting H0 there is an association between the cgzone vs Cover_Type.              
Since the P-value(0)<alpha(0.05) rejecting H0 there is an association between the Soil vs Cover_Type.              
Since the P-value(0)<alpha(0.05) rejecting H0 there is an association between the Soil vs Wilderness_Area.